SOURCES:= gui_vent_mensaje_aviso.cpp \
    gui_vent_pregunta.cpp \
    gui_vent_pregunta_sino.cpp

INCS:= gui_vent.h \
    gui_vent_mensaje_aviso.h \
    gui_vent_modal.h \
    gui_vent_pregunta.h \
    gui_vent_pregunta_sino.h

# NOMBRE DE LA BIBLIOTECA
LIB = gui_etc
INSTALL_INC=$(CPP_INCLUDE)/gui


include $(GUI_VENT_COMPRULES)


