# para probar el código
BASE=../..
SOURCES= main.cpp \
	$(BASE)/gui_fl.cpp \
	$(BASE)/gui_tipos.cpp \
	$(BASE)/gui_base.cpp \
	$(BASE)/gui_ventana.cpp \
	$(BASE)/gui_widget.cpp \
	$(BASE)/gui_widget_etcon.cpp \
	$(BASE)/gui_boton.cpp \
	$(BASE)/gui_boton_doble.cpp	\
	$(BASE)/gui_grupo_de_controles.cpp

BIN=xx


include $(GUI_CORE_COMPRULES)


