# para probar el código
BASE=../..
SOURCES= main.cpp \
	$(BASE)/gui_tipos.cpp

BIN=xx

# BIBLIOTECAS CON LAS QUE ENLAZAMOS AL COMPILAR
#USER_LIBS=boost_filesystem\
	  boost_system
USER_LIBS=alp


include $(GUI_CORE_COMPRULES)


