# para probar el código
BASE=../..
SOURCES= main.cpp \
	$(BASE)/gui_fl.cpp \
	$(BASE)/gui_tipos.cpp \
	$(BASE)/gui_base.cpp \
	$(BASE)/gui_ventana.cpp \
	$(BASE)/gui_widget.cpp \
	$(BASE)/gui_widget_etcon.cpp \
	$(BASE)/gui_boton.cpp	\
	$(BASE)/gui_input_int.cpp	\
	$(BASE)/gui_circular_bool.cpp	\
	$(BASE)/gui_maquetador.cpp	\
	$(BASE)/gui_grupo_de_controles.cpp \
	$(BASE)/gui_combo_strings_mas.cpp

BIN=xx

# BIBLIOTECAS CON LAS QUE ENLAZAMOS AL COMPILAR
#USER_LIBS=boost_filesystem\
	  boost_system
USER_LIBS=alp


include $(GUI_CORE_COMPRULES)


