SOURCES= gui_fl_visor.cpp \
		 gui_visor.cpp


INCS= 	gui.h \
		gui_fl_visor.h \
	  	gui_visor.h


# NOMBRE DE LA BIBLIOTECA
LIB = gui_visor
INSTALL_INC=$(CPP_INCLUDE)/gui


include $(GUI_VISOR_COMPRULES)


