SOURCES:= gui_fl.cpp \
    gui_tipos.cpp \
    gui_ventana.cpp \
    gui_widget.cpp \
    gui_base.cpp \
    gui_grupo_de_controles.cpp \
    gui_boton_bool.cpp \
    gui_boton.cpp \
    gui_boton_doble.cpp \
    gui_check_bool.cpp \
    gui_circular_bool.cpp \
    gui_cliente.cpp \
    gui_input_int.cpp \
    gui_input_string.cpp \
    gui_combo_strings_mas.cpp \
    gui_widget_etcon.cpp \
    gui_maquetador.cpp
 

INCS:= 	gui_core.h \
	gui_tipos.h \
    gui_fl.h \
	gui_ventana.h \
	gui_widget.h \
	gui_base.h \
	gui_grupo_de_controles.h \
    gui_menu_bar.h \
    gui_etiqueta.h \
	gui_boton_bool.h \
	gui_boton_doble.h \
	gui_boton.h \
	gui_check_bool.h \
	gui_circular_bool.h \
	gui_cliente.h \
	gui_combo_strings.h \
    gui_combo_strings_mas.h \
	gui_input_int.h \
	gui_input_string.h \
    gui_timer.h \
	gui_widget_etcon.h \
	gui_maquetador.h

# NOMBRE DE LA BIBLIOTECA
LIB = gui_core

INSTALL_INC=$(CPP_INCLUDE)/gui


include $(GUI_CORE_COMPRULES)


