# para probar el código
BASE=../..
SOURCES= test_visor03.cpp \
	$(BASE)/gui_fl.cpp \
	$(BASE)/gui_tipos.cpp \
	$(BASE)/gui_base.cpp \
	$(BASE)/gui_ventana.cpp \
	$(BASE)/gui_widget.cpp \
	$(BASE)/gui_widget_etcon.cpp \
	$(BASE)/gui_fl_visor.cpp \
	$(BASE)/gui_visor.cpp \
	$(BASE)/gui_boton.cpp	\
	$(BASE)/gui_input_int.cpp	\
	$(BASE)/gui_maquetador.cpp

BIN=xx

# BIBLIOTECAS CON LAS QUE ENLAZAMOS AL COMPILAR
#USER_LIBS=boost_filesystem\
	  boost_system
USER_LIBS=alp img 


include $(GUI_CORE_COMPRULES)


